In [12]:
import numpy as np
dataset_filename = 'affinity_dataset.txt'
X = np.loadtxt(dataset_filename)
n_samples, n_features = X.shape
print("This dataset has {0} samples and {1} features".format(n_samples, n_features))
print X[:5]

This dataset has 100 samples and 5 features
[[ 0.  0.  1.  1.  1.]
 [ 1.  1.  0.  1.  0.]
 [ 1.  0.  1.  1.  0.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  1.  0.  0.  1.]]


In [10]:
features = ["bread", "milk", "cheese", "apples", "bananas"]

In [8]:
num_apple_purchases = 0
for sample in X:
    if sample[3] == 1: # this person bought apple
        num_apple_purchases += 1
print('{0} people bought apples'.format(num_apple_purchases))

36 people bought apples


In [13]:
from collections import defaultdict
# Now compute for all possible rules
valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occurences = defaultdict(int)

for sample in X:
    for premise in range(n_features):
        if sample[premise] == 0: continue
        # Record that the premise was bought in another transaction
        num_occurences[premise] += 1
        for conclusion in range(n_features):
            if premise == conclusion:  # It makes little sense to measure if X -> X.
                continue
            if sample[conclusion] == 1:
                # This person also bought the conclusion item
                valid_rules[(premise, conclusion)] += 1
            else:
                # This person bought the premise, but not the conclusion
                invalid_rules[(premise, conclusion)] += 1
support = valid_rules
confidence = defaultdict(float)
for premise, conclusion in valid_rules.keys():
    confidence[(premise, conclusion)] = valid_rules[(premise, conclusion)] / num_occurences[premise]

In [14]:
for premise, conclusion in confidence:
    premise_name = features[premise]
    conclusion_name = features[conclusion]
    print("Rule: If a person buys {0} they will also buy {1}".format(premise_name, conclusion_name))
    print(" - Confidence: {0:.3f}".format(confidence[(premise, conclusion)]))
    print(" - Support: {0}".format(support[(premise, conclusion)]))
    print("")

Rule: If a person buys bread they will also buy milk
 - Confidence: 0.000
 - Support: 14

Rule: If a person buys milk they will also buy cheese
 - Confidence: 0.000
 - Support: 7

Rule: If a person buys apples they will also buy cheese
 - Confidence: 0.000
 - Support: 25

Rule: If a person buys milk they will also buy apples
 - Confidence: 0.000
 - Support: 9

Rule: If a person buys bread they will also buy apples
 - Confidence: 0.000
 - Support: 5

Rule: If a person buys apples they will also buy bread
 - Confidence: 0.000
 - Support: 5

Rule: If a person buys apples they will also buy bananas
 - Confidence: 0.000
 - Support: 21

Rule: If a person buys apples they will also buy milk
 - Confidence: 0.000
 - Support: 9

Rule: If a person buys milk they will also buy bananas
 - Confidence: 0.000
 - Support: 19

Rule: If a person buys cheese they will also buy bananas
 - Confidence: 0.000
 - Support: 27

Rule: If a person buys cheese they will also buy bread
 - Confidence: 0.000
 - Suppor